name: tighubad
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  flutter_native_splash: ^2.4.6
  provider: ^6.1.5
  lottie: 3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/THLogo-blue 1.png
    - assets/images/THLogowhite.png
    - assets/images/unsplash_0apZjDdRS5o.png
    - assets/images/Vector.png
    - assets/images/Vector-2.png
    - assets/images/Vector -3.png
    - assets/images/Vector-4.png
    - assets/images/undraw_winners_re_wr1l 1.png
    - assets/images/Logo.png
    - assets/Animation - 1746653407687.json

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter_18pt-Italic.ttf
          style: italic

# ❗️flutter_native_splash bu hissənin xaricində olmalıdır!
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/b1ecc104-f10a-4109-bdd9-e20054e701a8.png
  android: true
  ios: true
  web: false
  fullscreen: true
